spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080/likelion-db
    username: root
    password: 1q2w3e4r
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database : mysql
    hibernate.ddl-auto : update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com: debug

#한글깨짐에러해결
server:
  servlet:
    encoding:
      force: true

jwt:
  token:
    secret: secret