name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # 어떤 OS에서 실행될지
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # test 건너뛰고 빌드
    - name: run build
      run: ./gradlew clean build -x test
  
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - name: build and release to DockerHub
      env:
        NAME: minry20415 # 계정 명
        REPO: hospital-information-api # 레포 이름
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest
  
  # 배포 스크립트 작성
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:
      - name: Docker run
        run: |
              docker ps -q --filter "name=hospital-information-api" | grep -q . && docker stop "hospital-information-api" && docker rmi  "minry20415/hospital-information-api"
              sudo docker pull minry20415/hospital-information-api:latest
              docker run -d --name hospital-information-api -e SPRING_DATASOURCE_URL=jdbc:mysql://ec2-43-200-2-61.ap-northeast-2.compute.amazonaws.com/hospital-review-db -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=minmin5588 -e JWT_TOKEN_SECRET=totoken -p 8080:8081 minry20415/hospital-information-api:latest
